### ISSUE TITLE
gitdb doesn't exist for python3

### ISSUE THREAD

**Issue by zyxep** [CloudBotIRC/CloudBot#10]
Hi.

I updated my bot to latest version, and wanted to add some API keys like to the weather.

But when i started my server i got this error.
```
[23:19:54][ERROR] Error loading update.py:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 20, in _init_externals
    import gitdb
ImportError: No module named 'gitdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyxep/phalconphpBot/cloudbot/plugin.py", line 144, in load_plugin
    plugin_module = importlib.import_module(module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/zyxep/phalconphpBot/plugins/update.py", line 1, in <module>
    from git import Repo
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 28, in <module>
    _init_externals()
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 22, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
```

this is my whole startup

```
$ python3.4 -m cloudbot
CloudBot3 <http://git.io/refresh>
[23:19:53][INFO] Enabling developer option: config reloading.
[23:19:53][INFO] Enabling developer option: file debug
[23:19:53][INFO] [freenode] Created permission manager for freenode.
[23:19:53][INFO] [freenode] Reloading permissions for freenode.
[23:19:53][INFO] Loaded command weather from weather.py
[23:19:53][INFO] Loaded command xkcd from xkcd.py
[23:19:53][INFO] Loaded regex xkcd_url from xkcd.py
[23:19:53][INFO] Registering tables for factoids
[23:19:53][INFO] Loaded command choose from choose.py
[23:19:53][INFO] Loaded command debug from debug.py
[23:19:53][INFO] Loaded command wiki/w/wikipedia from wikipedia.py
[23:19:53][INFO] Loaded command memory from system.py
[23:19:53][INFO] Loaded command uptime from system.py
[23:19:53][INFO] Loaded command pid from system.py
[23:19:53][INFO] Loaded command system from system.py
[23:19:53][INFO] Loaded command domain/domainr from domainr.py
[23:19:53][INFO] Loaded command help from help.py
[23:19:54][INFO] Loaded command mlia from mlia.py
[23:19:54][INFO] Loaded command mcping/mcp from minecraft_ping.py
[23:19:54][INFO] Loaded command rt from rottentomatoes.py
[23:19:54][INFO] Loaded command reddit from reddit.py
[23:19:54][INFO] Loaded regex reddit_url from reddit.py
[23:19:54][INFO] Loaded command urban/u from urban.py
[23:19:54][INFO] Loaded command isup from pagecheck.py
[23:19:54][INFO] Loaded command down/offline/up from pagecheck.py
[23:19:54][INFO] Loaded command coin from coin.py
[23:19:54][INFO] Loaded command potato from foods.py
[23:19:54][INFO] Loaded command cookie from foods.py
[23:19:54][INFO] Loaded command cake from foods.py
[23:19:54][INFO] Loaded command imdb from imdb.py
[23:19:54][INFO] Loaded regex imdb_url from imdb.py
[23:19:54][INFO] Loaded command beats from time_plugin.py
[23:19:54][INFO] Loaded command time from time_plugin.py
[23:19:54][INFO] Loaded regex ctcp_ping from core_ctcp.py
[23:19:54][INFO] Loaded regex ctcp_version from core_ctcp.py
[23:19:54][INFO] Loaded regex ctcp_time from core_ctcp.py
[23:19:54][INFO] Loaded command quote/q from quote.py
[23:19:54][INFO] Loaded command googleurl from googleurlparse.py
[23:19:54][INFO] Loaded command mcstatus from minecraft_status.py
[23:19:54][INFO] Loaded command word from wordoftheday.py
[23:19:54][INFO] Loaded command mcuser/haspaid/mcpaid from minecraft_user.py
[23:19:54][INFO] Loaded command rb from rss.py
[23:19:54][INFO] Loaded command rss/feed from rss.py
[23:19:54][INFO] Registering tables for regex_chans
[23:19:54][INFO] Loaded command ping from ping.py
[23:19:54][INFO] Loaded command recipe from recipe.py
[23:19:54][INFO] Loaded command dinner from recipe.py
[23:19:54][INFO] Loaded sieve sieve_suite from core_sieve.py
[23:19:54][INFO] Loaded command roll/dice from dice.py
[23:19:54][INFO] Loaded irc raw on_kick (KICK) from core_tracker.py
[23:19:54][INFO] Loaded irc raw on_join (JOIN) from core_tracker.py
[23:19:54][INFO] Loaded irc raw on_nick (NICK) from core_tracker.py
[23:19:54][INFO] Loaded command namegen from namegen.py
[23:19:54][INFO] Loaded command metacritic/mc from metacritic.py
[23:19:54][INFO] Loaded command imgur from imgur.py
[23:19:54][INFO] Loaded command spotify/sptrack from spotify.py
[23:19:54][INFO] Loaded command spalbum from spotify.py
[23:19:54][INFO] Loaded command spartist from spotify.py
[23:19:54][INFO] Loaded regex spotify_url from spotify.py
[23:19:54][INFO] Loaded command wa/wolframalpha/calc/math from wolframalpha.py
[23:19:54][INFO] Loaded command password from password.py
[23:19:54][INFO] Loaded command rpass/rpassword/readablepassword from password.py
[23:19:54][INFO] Loaded command mccraft/mcrecipe from minecraft_items.py
[23:19:54][INFO] Loaded command mcitem/mcid from minecraft_items.py
[23:19:54][INFO] Loaded command slap from slap.py
[23:19:54][INFO] Loaded command portal2dlc from valvesounds.py
[23:19:54][INFO] Loaded command portalmusic/portal1music from valvesounds.py
[23:19:54][INFO] Loaded command portal2 from valvesounds.py
[23:19:54][INFO] Loaded command tf2sound/tf2 from valvesounds.py
[23:19:54][INFO] Loaded command tf2music from valvesounds.py
[23:19:54][INFO] Loaded command portal2music from valvesounds.py
[23:19:54][INFO] Loaded command portal2dlc2/portal2pti from valvesounds.py
[23:19:54][INFO] Loaded command portal/portal1 from valvesounds.py
[23:19:54][INFO] Loaded command validate/w3c from validate.py
[23:19:54][INFO] Loaded command mcwiki from minecraft_wiki.py
[23:19:54][INFO] Loaded command slogan from slogan.py
[23:19:54][INFO] Loaded command suggest from suggest.py
[23:19:54][INFO] Loaded command drama from drama.py
[23:19:54][INFO] Loaded command pre/scene from scene.py
[23:19:54][INFO] Loaded command osrc from osrc.py
[23:19:54][INFO] Loaded regex vimeo_url from vimeo.py
[23:19:54][INFO] Loaded command fact from fact.py
[23:19:54][INFO] Loaded command e/etymology from dictionary.py
[23:19:54][INFO] Loaded command dictionary/define from dictionary.py
[23:19:54][INFO] Loaded command qrcode/qr from qrcode.py
[23:19:54][INFO] Loaded command steam from steam.py
[23:19:54][INFO] Loaded regex steam_url from steam.py
[23:19:54][INFO] Loaded command hulu from hulu.py
[23:19:54][INFO] Loaded regex hulu_url from hulu.py
[23:19:54][INFO] Loaded command ltc/litecoin from cryptocoins.py
[23:19:54][INFO] Loaded command btc/bitcoin from cryptocoins.py
[23:19:54][INFO] Loaded command seen from history.py
[23:19:54][INFO] Loaded command resethistory from history.py
[23:19:54][INFO] Loaded event chat_tracker (EventType.action,EventType.message) from history.py
[23:19:54][INFO] Loaded command rdio from rdio.py
[23:19:54][INFO] Loaded command rdiot from rdio.py
[23:19:54][INFO] Loaded command rdioar from rdio.py
[23:19:54][INFO] Loaded command rdioal from rdio.py
[23:19:54][INFO] Loaded regex rdio_url from rdio.py
[23:19:54][INFO] Loaded command newegg from newegg.py
[23:19:54][INFO] Loaded regex newegg_url from newegg.py
[23:19:54][INFO] Loaded command reverse from utility.py
[23:19:54][INFO] Loaded command swapcase from utility.py
[23:19:54][INFO] Loaded command unescape from utility.py
[23:19:54][INFO] Loaded command hash from utility.py
[23:19:54][INFO] Loaded command upper from utility.py
[23:19:54][INFO] Loaded command base64 from utility.py
[23:19:54][INFO] Loaded command wrainbow from utility.py
[23:19:54][INFO] Loaded command escape from utility.py
[23:19:54][INFO] Loaded command titlecase from utility.py
[23:19:54][INFO] Loaded command capitalise/capitalize from utility.py
[23:19:54][INFO] Loaded command rot13 from utility.py
[23:19:54][INFO] Loaded command isbase64/checkbase64 from utility.py
[23:19:54][INFO] Loaded command munge from utility.py
[23:19:54][INFO] Loaded command superscript from utility.py
[23:19:54][INFO] Loaded command rainbow from utility.py
[23:19:54][INFO] Loaded command debase64/unbase64 from utility.py
[23:19:54][INFO] Loaded command usa from utility.py
[23:19:54][INFO] Loaded command lower from utility.py
[23:19:54][INFO] Loaded command length from utility.py
[23:19:54][INFO] Loaded command steamcalc/sc from steam_calc.py
[23:19:54][INFO] Loaded command cypher from cypher.py
[23:19:54][INFO] Loaded command decypher from cypher.py
[23:19:54][INFO] Loaded command plpaste from plpaste.py
[23:19:54][INFO] Loaded command armory/armoury from wow.py
[23:19:54][INFO] Loaded command translate from google_translate.py
[23:19:54][INFO] Loaded command answer from yahooanswers.py
[23:19:54][INFO] Loaded command issues from github.py
[23:19:54][INFO] Loaded command snopes from snopes.py
[23:19:54][INFO] Loaded irc raw onjoin (004) from core_misc.py
[23:19:54][INFO] Loaded irc raw keep_alive (004) from core_misc.py
[23:19:54][INFO] Loaded irc raw invite (INVITE) from core_misc.py
[23:19:54][INFO] Loaded command unban from op.py
[23:19:54][INFO] Loaded command ban from op.py
[23:19:54][INFO] Loaded command deop from op.py
[23:19:54][INFO] Loaded command unquiet from op.py
[23:19:54][INFO] Loaded command lock from op.py
[23:19:54][INFO] Loaded command devoice from op.py
[23:19:54][INFO] Loaded command voice from op.py
[23:19:54][INFO] Loaded command mute from op.py
[23:19:54][INFO] Loaded command unmute from op.py
[23:19:54][INFO] Loaded command op from op.py
[23:19:54][INFO] Loaded command quiet from op.py
[23:19:54][INFO] Loaded command remove from op.py
[23:19:54][INFO] Loaded command kick from op.py
[23:19:54][INFO] Loaded command unlock from op.py
[23:19:54][INFO] Loaded command topic from op.py
[23:19:54][INFO] Loaded command lmgtfy/gfy from lmgtfy.py
[23:19:54][INFO] Loaded command kernel from kernel.py
[23:19:54][INFO] Loaded command raw from admin.py
[23:19:54][INFO] Loaded command uperms from admin.py
[23:19:54][INFO] Loaded command gusers from admin.py
[23:19:54][INFO] Loaded command cycle from admin.py
[23:19:54][INFO] Loaded command join from admin.py
[23:19:54][INFO] Loaded command groups/permgroups/listgroups from admin.py
[23:19:54][INFO] Loaded command nick from admin.py
[23:19:54][INFO] Loaded command say from admin.py
[23:19:54][INFO] Loaded command message/sayto from admin.py
[23:19:54][INFO] Loaded command adduser from admin.py
[23:19:54][INFO] Loaded command restart from admin.py
[23:19:54][INFO] Loaded command me/act from admin.py
[23:19:54][INFO] Loaded command deluser from admin.py
[23:19:54][INFO] Loaded command ugroups from admin.py
[23:19:54][INFO] Loaded command stop/quit from admin.py
[23:19:54][INFO] Loaded command gperms from admin.py
[23:19:54][INFO] Loaded command part from admin.py
[23:19:54][INFO] Loaded regex correction from correction.py
[23:19:54][INFO] Loaded command python/py from python.py
[23:19:54][INFO] Loaded command note/notes from notes.py
[23:19:54][INFO] Loaded regex newgrounds_url from newgrounds.py
[23:19:54][INFO] Loaded command youtime/ytime from youtube.py
[23:19:54][INFO] Loaded command youtube/y/you/yt from youtube.py
[23:19:54][INFO] Loaded regex youtube_url from youtube.py
[23:19:54][INFO] Loaded regex ytplaylist_url from youtube.py
[23:19:54][INFO] Loaded command googleimage/image/gis from google.py
[23:19:54][INFO] Loaded command google/search/g from google.py
[23:19:54][ERROR] Error loading update.py:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 20, in _init_externals
    import gitdb
ImportError: No module named 'gitdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyxep/phalconphpBot/cloudbot/plugin.py", line 144, in load_plugin
    plugin_module = importlib.import_module(module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/zyxep/phalconphpBot/plugins/update.py", line 1, in <module>
    from git import Repo
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 28, in <module>
    _init_externals()
  File "/usr/local/lib/python3.4/dist-packages/GitPython-0.3.1-py3.4.egg/git/__init__.py", line 22, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
[23:19:54][INFO] Loaded command stock from stock.py
[23:19:54][INFO] Loaded command twviewers/twitchviewers from twitch.py
[23:19:54][INFO] Loaded regex twitch_url from twitch.py
[23:19:54][INFO] Loaded regex multitwitch_url from twitch.py
[23:19:54][INFO] Registering tables for tell
[23:19:54][INFO] Registering tables for dbtest
[23:19:54][INFO] Loaded command spell from spellcheck.py
[23:19:54][INFO] Loaded command title from title.py
[23:19:54][INFO] Loaded command brainfuck/bf from brainfuck.py
[23:19:54][INFO] Loaded command tv/tv_next from tvdb.py
[23:19:54][INFO] Loaded command tv_prev/tv_last from tvdb.py
[23:19:54][INFO] Loaded command lyrics from lyrics.py
[23:19:54][INFO] Loaded command bans/fishbans from fishbans.py
[23:19:54][INFO] Loaded command bancount from fishbans.py
[23:19:54][INFO] Loaded command lastfm/l from lastfm.py
[23:19:54][INFO] Loaded regex soundcloud_url from soundcloud.py
[23:19:54][INFO] Loaded regex sndsc_url from soundcloud.py
[23:19:54][INFO] Loaded command flushlog from log.py
[23:19:54][INFO] Loaded irc raw console_log (*) from log.py
[23:19:54][INFO] Loaded irc raw log (*) from log.py
[23:19:54][INFO] Loaded irc raw log_raw (*) from log.py
[23:19:54][INFO] Loaded command expand from shorten.py
[23:19:54][INFO] Loaded command isgd from shorten.py
[23:19:54][INFO] Loaded command googl from shorten.py
[23:19:54][INFO] Loaded command gitio from shorten.py
[23:19:54][INFO] Loaded command shorten from shorten.py
[23:19:54][INFO] Loaded command twitter/tw/twatter from twitter.py
[23:19:54][INFO] Loaded command twuser/twinfo from twitter.py
[23:19:54][INFO] Loaded regex twitter_url from twitter.py
[23:19:54][INFO] Loaded command lart from attacks.py
[23:19:54][INFO] Loaded command insult from attacks.py
[23:19:54][INFO] Loaded command kill from attacks.py
[23:19:54][INFO] Loaded command flirt from attacks.py
[23:19:54][INFO] Loaded command fortune from fortune.py
[23:19:54][INFO] Loaded command 8ball/8/eightball from eightball.py
[23:19:54][INFO] Loaded command horoscope from horoscope.py
[23:19:54][INFO] Loaded command ignored from ignore.py
[23:19:54][INFO] Loaded command unignore from ignore.py
[23:19:54][INFO] Loaded command ignore from ignore.py
[23:19:54][INFO] Loaded sieve ignore_sieve from ignore.py
[23:19:54][INFO] Loaded command decrypt from encrypt.py
[23:19:54][INFO] Loaded command encrypt from encrypt.py
[23:19:54][INFO] Loaded command pymdiff from profiling.py
[23:19:54][INFO] Loaded command objgrowth from profiling.py
[23:19:54][INFO] Loaded command objtypes from profiling.py
[23:19:54][INFO] Loaded command pymsummary from profiling.py
[23:19:54][INFO] Loaded command threaddump from profiling.py
[23:19:54][INFO] Loaded command geoip from geoip.py
[23:19:54][INFO] Loaded command tell from tell.py
[23:19:54][INFO] Loaded command showtells from tell.py
[23:19:54][INFO] Loaded event tellinput (EventType.message) from tell.py
[23:19:54][INFO] Loaded command dbadduser from dbtest.py
[23:19:54][INFO] Loaded command select from dbtest.py
[23:19:54][INFO] Loaded command disableregex from regex_chans.py
[23:19:54][INFO] Loaded command enableregex from regex_chans.py
[23:19:54][INFO] Loaded command regexstatus from regex_chans.py
[23:19:54][INFO] Loaded command resetregex from regex_chans.py
[23:19:54][INFO] Loaded command listregex from regex_chans.py
[23:19:54][INFO] Loaded sieve sieve_regex from regex_chans.py
[23:19:54][INFO] Loaded command listfactoids from factoids.py
[23:19:54][INFO] Loaded command info from factoids.py
[23:19:54][INFO] Loaded command f/forget from factoids.py
[23:19:54][INFO] Loaded command r/remember from factoids.py
[23:19:54][INFO] Loaded regex factoid from factoids.py
[23:19:55][INFO] Loaded command bukget/plugin from minecraft_bukget.py
[23:19:55][INFO] Loaded command randomplugin from minecraft_bukget.py
[23:19:55][INFO] Loaded command fml from fmylife.py
[23:19:55][INFO] [freenode] Connecting
[23:19:55][INFO] [freenode] >> NICK :phalconphp
[23:19:55][INFO] [freenode] >> USER phalconphp 3 * :CloudBotRefresh - http://cloudbot.pw
[23:19:55][INFO] [freenode:*] -kornbluth.freenode.net- *** Looking up your hostname...
[23:19:55][INFO] [freenode:*] -kornbluth.freenode.net- *** Checking Ident
[23:19:55][INFO] [freenode:*] -kornbluth.freenode.net- *** Found your hostname
^C[23:20:05][INFO] Stopping bot.
[23:20:05][INFO] [freenode] >> QUIT :Killed
[23:20:05][INFO] ONJOIN hook triggered.
```

I just ran a ```pip install -r requirements.txt --upgrade```

No fix there.

**Comment by lukeroge** [comment]
I think we can close this issue at this point.
