### ISSUE TITLE
Rottentomatoes plugin KeyError on total

### ISSUE THREAD

**Issue by BigMarlin1** [CloudBotIRC/CloudBot#107]
ERROR:cloudbot:Error in hook rottentomatoes:rotten_tomatoes
Traceback (most recent call last):
  File "/home/dywtk/CloudBot/cloudbot/plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "/usr/local/opt/python-3.4.2/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/opt/python-3.4.2/lib/python3.4/asyncio/tasks.py", line 285, in _wakeup
    value = future.result()
  File "/usr/local/opt/python-3.4.2/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/local/opt/python-3.4.2/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dywtk/CloudBot/cloudbot/plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "/home/dywtk/CloudBot/plugins/rottentomatoes.py", line 53, in rotten_tomatoes
    review_count = reviews['total']
KeyError: 'total'

**Comment by edwardslabs** [comment]
I think this is fixed by #119
