### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by MineDev2014** [CloudBotIRC/CloudBot#11]
I can't seem to be able to use the latest version of this repository, older versions (e.g. fea70da9a58a147820814beb18b28ff0c1bb0d29) work fine but the latest one gives me this error when connecting:

```
[19:26:14][INFO] [irc] Connecting
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bot/CloudBotRefresh/cloudbot/__main__.py", line 92, in <module>
    main()
  File "/home/bot/CloudBotRefresh/cloudbot/__main__.py", line 64, in main
    restart = cloudbot.run()
  File "/home/bot/CloudBotRefresh/cloudbot/bot.py", line 113, in run
    self.loop.run_until_complete(self._init_routine())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 298, in _step
    result = coro.throw(exc)
  File "/home/bot/CloudBotRefresh/cloudbot/bot.py", line 188, in _init_routine
    yield from asyncio.gather(*[conn.connect() for conn in self.connections], loop=self.loop)
  File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "/home/bot/CloudBotRefresh/cloudbot/clients/irc.py", line 104, in connect
    lambda: _IrcProtocol(self), host=self.server, port=self.port, ssl=self.ssl_context, local_addr=self.local_bind)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 385, in create_connection
    laddr_infos = f2.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Am I doing something wrong?

**Comment by bcizzo** [comment]
@MineDev2014 Could you elaborate on what you mean by "2 new configuration property", I am having this same error! Thanks!
