### ISSUE TITLE
Issue with the Rotten Tomatoes Command

### ISSUE THREAD

**Issue by KamranMackey** [CloudBotIRC/CloudBot#117]
When trying to fetch results for a movie on Rotten Tomatoes, it always spits up some kind of error, like the one below

```
Traceback (most recent call last):
  File "c:\Ralybot\cloudbot\plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)  
File "c:\Python34\lib\asyncio\futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\Python34\lib\asyncio\tasks.py", line 287, in _wakeup
    value = future.result()
  File "c:\Python34\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "c:\Python34\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\Ralybot\cloudbot\plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "c:\Ralybot\plugins\rottentomatoes.py", line 55, in rotten_tomatoes
    fresh = critics_score * review_count / 100
TypeError: unsupported operand type(s) for *: 'int' and 'dict'
```
I really would like it if this could be fixed, as it's a real pain in the butt to deal with.

**Comment by foxlet** [comment]
Issue has been fixed in a PR.
