### ISSUE TITLE
ImportError: No module named 'sqlalchemy'

### ISSUE THREAD

**Issue by Chiisato** [CloudBotIRC/CloudBot#149]
Clean ubuntu install, followed readme, I've installed sqlalchemy with pip and still getting ImportError: No module named 'sqlalchemy'

Full traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chisato/Downloads/CloudBotRefresh-python3.4/cloudbot/__main__.py", line 19, in <module>
    from cloudbot.bot import CloudBot
  File "/home/chisato/Downloads/CloudBotRefresh-python3.4/cloudbot/bot.py", line 8, in <module>
    from sqlalchemy import create_engine
ImportError: No module named 'sqlalchemy'

**Comment by Red-M** [comment]
Something like this wouldn't go unnoticed, so I'm going to say, check your install and to make sure you installed it correctly.
What was the output of pip install sqlalchemy.
Did it have any errors.
Have you installed it as another user or as root or the current user on the machine.

I'm asking this many questions because you've said that you followed the instruction and it didn't work so therefore there is something wrong with the software.

**Comment by Chiisato** [comment]
Nevermind me, appears I used pip for python 2.7 instead of 3.4, closing.
