### ISSUE TITLE
bot don't do a thing with CTCP

### ISSUE THREAD

**Issue by Jeebeevee** [CloudBotIRC/CloudBot#167]
When i send a CTCP request to my Cloudbot it don't do a thing.with the action.

/ctcp bot VERSION

log:
[21:39:22] [ERROR] Error in hook log:console_log
Traceback (most recent call last):
  File "/home/jelmer/douwe/cloudbot/plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "/usr/lib/python3.4/asyncio/futures.py", line 387, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 276, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jelmer/douwe/cloudbot/plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "/home/jelmer/douwe/plugins/log.py", line 240, in console_log
    text = format_event(event)
  File "/home/jelmer/douwe/plugins/log.py", line 74, in format_event
    return format_irc_event(event, args)
  File "/home/jelmer/douwe/plugins/log.py", line 98, in format_irc_event
    ctcp_command, ctcp_message = event.irc_ctcp_text.split(None, 1)
ValueError: need more than 1 value to unpack
[21:39:22] [ERROR] Error in hook log:log
Traceback (most recent call last):
  File "/home/jelmer/douwe/cloudbot/plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "/usr/lib/python3.4/asyncio/futures.py", line 387, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 276, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jelmer/douwe/cloudbot/plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "/home/jelmer/douwe/plugins/log.py", line 223, in log
    text = format_event(event)
  File "/home/jelmer/douwe/plugins/log.py", line 74, in format_event
    return format_irc_event(event, args)
  File "/home/jelmer/douwe/plugins/log.py", line 98, in format_irc_event
    ctcp_command, ctcp_message = event.irc_ctcp_text.split(None, 1)
ValueError: need more than 1 value to unpack

i have core_ctcp.py plugin active.

also i have a made a personal plugin with a ctcp action with more variables (like: /ctcp bot CTCT_NAME action). With a test to send a notice/ctcp back, but it don't do anything and also nothing in the log.

code:

@hook.regex(r'^\x01CTCP_TEST .*\x01$')
def my_ctcp_hook(match, notice=None):
    ctcp_contents = match.group(1)
    notice('%s' % ctcp_contents)

**Comment by astrutt** [comment]
I can reproduce this as well. I wish it did work though.. It's very helpful to have the bot respond to CTCP to be compatible with some networks, also it could help advertise the type of bot and where to get it without using .about

**Comment by pangeacake** [comment]
I have created pull request #243 which fixes this.

**Comment by daboross** [comment]
The error message is fixed with @pangeacake's pull request, but the underlying issue remains.

I'm going to try to come up with something to fix the CTCP hooks, but I want to first find out *when* it was broken.

**Comment by daboross** [comment]
Should be fixed in https://github.com/CloudBotIRC/CloudBot/commit/bac4edf99a8aa624cef1d51c156c6d49c58dad0f.

**Comment by daboross** [comment]
Fixed (actually) in https://github.com/CloudBotIRC/CloudBot/commit/e3713e2d4b9604c45f41e444b9d3b4de486ecb44!
