### ISSUE TITLE
Cloudbot crashes on launch

### ISSUE THREAD

**Issue by TheFiZi** [CloudBotIRC/CloudBot#191]
Updated my bot last night from the master branch (I do this automatically every night) and Cloudbot won't launch now:

      Traceback (most recent call last):
        File "/data/apps/sa_cloudbot/python/lib/python3.4/runpy.py", line 170, in _run_module_as_main
          "__main__", mod_spec)
        File "/data/apps/sa_cloudbot/python/lib/python3.4/runpy.py", line 85, in _run_code
          exec(code, run_globals)
        File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/__main__.py", line 19, in <module>
          from cloudbot.bot import CloudBot
        File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/bot.py", line 21, in <module>
          from cloudbot.clients.irc import IrcClient
        File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/clients/irc.py", line 150
          for text in messages
                             ^
      SyntaxError: invalid syntax

Nothing else has changed in my system.

**Comment by TheFiZi** [comment]
Did a git pull. Same issue.

    python3 -m cloudbot
    
    Traceback (most recent call last):
      File "/data/apps/sa_cloudbot/python/lib/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/data/apps/sa_cloudbot/python/lib/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/__main__.py", line 19, in <module>
        from cloudbot.bot import CloudBot
      File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/bot.py", line 21, in <module>
        from cloudbot.clients.irc import IrcClient
      File "/data/apps/sa_cloudbot/CloudBotRefresh/cloudbot/clients/irc.py", line 150
        for text in messages
                           ^
    SyntaxError: invalid syntax

**Comment by edwardslabs** [comment]
The fix has not yet been merged.

**Comment by TheFiZi** [comment]
Oops. Sorry about that.

**Comment by TheFiZi** [comment]
That fixed it.
