### ISSUE TITLE
Fetching imgur image does not work

### ISSUE THREAD

**Issue by Chiisato** [CloudBotIRC/CloudBot#196]
Getting this

Traceback (most recent call last):
  File "/home/Chi/Cloudbot/cloudbot/plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "/usr/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 351, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/Chi/Cloudbot/cloudbot/plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "/home/Chi/Cloudbot/plugins/imgur.py", line 108, in imgur
    reddit_url = web.try_shorten("http://reddit.com" + item.reddit_comments)
AttributeError: 'GalleryImage' object has no attribute 'reddit_comments'

**Comment by edwardslabs** [comment]
@lukeroge  I can reproduce this for any subreddit imgur search. I can't find any reference to reddit_comments imgurpython did they remove it or was that attribute sourced from somewhere else?

**Comment by Chiisato** [comment]
Pretty sure it's from here

https://api.imgur.com/endpoints/gallery#subreddit

"Response Model	Gallery Images with 'reddit_comments' url"

**Comment by Chiisato** [comment]
Anything new on this?
