### ISSUE TITLE
Reminder error 

### ISSUE THREAD

**Issue by Afootpluto** [CloudBotIRC/CloudBot#204]
9:37:50] [ERROR] Error in hook remind:check_reminders
Traceback (most recent call last):
  File "/home/afootpluto/bot2/cloudbot/plugin.py", line 378, in _execute_hook
    out = yield from self._execute_hook_sync(hook, event)
  File "/home/afootpluto/bot2/cloudbot/plugin.py", line 357, in _execute_hook_sync
    return (yield from hook.function(*parameters))
  File "/home/afootpluto/bot2/plugins/remind.py", line 100, in check_reminders
    yield from add_reminder(async, db, network, remind_time, user)
TypeError: add_reminder() missing 3 required positional arguments: 'message', 'remind_time', and 'added_time'

**Comment by edwardslabs** [comment]
Same as #156

**Comment by Afootpluto** [comment]
I should have checked for duplicates. XD
