### ISSUE TITLE
The command "seen" does not work as intended.

### ISSUE THREAD

**Issue by sindastra** [CloudBotIRC/CloudBot#218]
I have already fixed the issue and will make a pull request.

The command "seen" should allow you to check when a specified user has last said something in a specified channel.

**Scenario**
Check when a specified user <nick> has said something in a specified channel <channel>.

**Test step**
Enter .seen <nick> <channel>

**Expected result**
If <nick> was "seen" in <channel>, it should return when <nick> was last seen in <channel>.
If <nick> was never seen in <channel>, it should return that <nick> has never been seen in <channel>.

**Actual outcome**
It returns that it can't look up that name, because it's impossible to use.

**Comment by tuxxy** [comment]
It appears that the maintainers don't look after this project anymore and, as such, have stopped reviewing pull requests.
If you submit this to my fork, I'll go ahead and merge it.

https://github.com/tuxxy/CloudBot

**Comment by Red-M** [comment]
In the sake of keeping the conversation in one stream please move it to PR #212

**Comment by whispy** [comment]
Any updates on a fix for this?

**Comment by sindastra** [comment]
> Any updates on a fix for this?

@whispy #219 Fixed issue #218

I already fixed it. Look at my pull request.

**Comment by whispy** [comment]
@sindastra The plugin crashes when I try to run it with your version.

Here's the traceback:
````[16:13:37] [ERROR] Error loading history.py:
Traceback (most recent call last):
  File "/whispy/awyeahbot-python3/cloudbot/plugin.py", line 147, in load_plugin
    plugin_module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/whispy/awyeahbot-python3/plugins/history.py", line 125
    return "I've never seen {} talking in {}.".format(name, chan)
                                                                ^
IndentationError: expected an indented block
````
