### ISSUE TITLE
<module> from cloudbot.bot import CloudBot

### ISSUE THREAD

**Issue by dannymichel** [CloudBotIRC/CloudBot#241]
```
-bash-4.1$ /usr/local/bin/python3.4 -m cloudbot
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/danny/CloudBot-master/cloudbot/__main__.py", line 19, in <module>
    from cloudbot.bot import CloudBot
  File "/home/danny/CloudBot-master/cloudbot/bot.py", line 8, in <module>
    from sqlalchemy import create_engine
ImportError: No module named 'sqlalchemy'
```

**Comment by Red-M** [comment]
Please report this issue to your local system administrator.

**Comment by edwardslabs** [comment]
sqlalchemy is not installed which more than likely means you did not run `pip3.4 install -r requirements.txt`

**Comment by daboross** [comment]
Closing as this is purely an issue of not installing required dependencies.
