### ISSUE TITLE
tvdb.py times out, no response in channel from bot. Prior to refresh, plugin worked as expected.

### ISSUE THREAD

**Issue by oracoraque** [CloudBotIRC/CloudBot#33]
```
[00:27:08] [ERROR] Error in hook tvdb:tv_next
Traceback (most recent call last):
  File "D:\CloudBotRefresh-python3.4\cloudbot\plugin.py", line 365, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "C:\Python34\lib\asyncio\futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Python34\lib\asyncio\tasks.py", line 285, in _wakeup
    value = future.result()
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result
    raise self._exception
  File "C:\Python34\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\CloudBotRefresh-python3.4\cloudbot\plugin.py", line 329, in _execute_hook_threaded
    return hook.function(*parameters)
  File "D:\CloudBotRefresh-python3.4\plugins\tvdb.py", line 73, in tv_next
    episodes = get_episodes_for_series(text, api_key)
  File "D:\CloudBotRefresh-python3.4\plugins\tvdb.py", line 27, in get_episodes_for_series
    series = http.get_xml(base_url + '%s/series/%s/all/en.xml' % (api_key, series_id))
  File "D:\CloudBotRefresh-python3.4\cloudbot\util\http.py", line 55, in get_xml
    return etree.fromstring(get(*args, **kwargs))
  File "D:\CloudBotRefresh-python3.4\cloudbot\util\http.py", line 38, in get
    return open(*args, **kwargs).read()
  File "D:\CloudBotRefresh-python3.4\cloudbot\util\http.py", line 96, in open
    return opener.open(request)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1202, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1177, in do_open
    r = h.getresponse()
  File "C:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python34\lib\socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by lukeroge** [comment]
I've changed a bunch of this plugin code with ee2d358, please advise if this issue still exists. As far as I can tell, TVDB was just timing out.
