### ISSUE TITLE
GoogleURL plugin needs update for Refresh

### ISSUE THREAD

**Issue by dmodoomsirius** [CloudBotIRC/CloudBot#48]
```py
[21:31:21] [INFO] [esper:dmod] <dmod> googleurl ci.builtborken.com
[21:31:21] [ERROR] Error in hook googleurlparse:googleurl
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Mikes_stuff\bots\CloudBot\cloudbot\plugin.py", li
ne 366, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_thre
aded, hook, event)
  File "C:\Python34\lib\asyncio\futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Python34\lib\asyncio\tasks.py", line 370, in _wakeup
    value = future.result()
  File "C:\Python34\lib\asyncio\futures.py", line 243, in result
    raise self._exception
  File "C:\Python34\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Admin\Desktop\Mikes_stuff\bots\CloudBot\cloudbot\plugin.py", li
ne 330, in _execute_hook_threaded
    return hook.function(*parameters)
  File "C:\Users\Admin\Desktop\Mikes_stuff\bots\CloudBot\plugins\googleurlparse.
py", line 13, in googleurl
    " like ? and chan = ?", (text.lower(), input.chan.lower())).fetchone()
AttributeError: 'builtin_function_or_method' object has no attribute 'chan'
```

**Comment by lukeroge** [comment]
I believe this is closed, thanks @foxlet
