### ISSUE TITLE
plugins/admin_bot.py stop and restart commands fail in 1.06

### ISSUE THREAD

**Issue by edwardslabs** [CloudBotIRC/CloudBot#98]
Running either the stop or restart commands in Cloudbot 1.06 fail with the following:

[00:42:25] [ERROR] Error in hook admin_bot:restart
Traceback (most recent call last):
  File "/home/andy/ircbot/testing/cbtest/cloudbot/plugin.py", line 378, in _execute_hook
    out = yield from self._execute_hook_sync(hook, event)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/plugin.py", line 357, in _execute_hook_sync
    return (yield from hook.function(*parameters))
  File "/home/andy/ircbot/testing/cbtest/plugins/admin_bot.py", line 223, in restart
    yield from bot.restart(reason=text)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/bot.py", line 175, in restart
    yield from self.stop(reason=reason, restart=True)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/bot.py", line 153, in stop
    if not connection.connected:
AttributeError: 'str' object has no attribute 'connected'
ERROR:cloudbot:Error in hook admin_bot:restart
Traceback (most recent call last):
  File "/home/andy/ircbot/testing/cbtest/cloudbot/plugin.py", line 378, in _execute_hook
    out = yield from self._execute_hook_sync(hook, event)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/plugin.py", line 357, in _execute_hook_sync
    return (yield from hook.function(*parameters))
  File "/home/andy/ircbot/testing/cbtest/plugins/admin_bot.py", line 223, in restart
    yield from bot.restart(reason=text)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/bot.py", line 175, in restart
    yield from self.stop(reason=reason, restart=True)
  File "/home/andy/ircbot/testing/cbtest/cloudbot/bot.py", line 153, in stop
    if not connection.connected:
AttributeError: 'str' object has no attribute 'connected'

**Comment by lukeroge** [comment]
ahhhhhhhhhhhhhh

**Comment by edwardslabs** [comment]
It looks like 2ac27c66fc0a57922218ada2b8266e9481894a01 fixed it for me. Thanks Luke!
